### ISSUE TITLE
MissingMethodException thrown in the co.freeside.betamax.tape.yaml.OrderedPropertyComparator class

### ISSUE THREAD

**Issue by restagner** [betamaxteam/betamax#161] opened 2015-06-08 14:30 UTC
I'm attempting to use betamax for the first time, and I'm enoucountering some odd behavior.  When I use betamax in conjunction with groovy-wslite to make RESTful calls, I receive the following exception when betamax attempts to write the information to tape

```text
groovy.lang.MissingMethodException: No signature of method: java.util.TreeSet.sort() is applicable for argument types: (co.freeside.betamax.tape.yaml.OrderedPropertyComparator) values: [co.freeside.betamax.tape.yaml.OrderedPropertyComparator@593b0259]
Possible solutions: sort(), sort(), sort(boolean), sort(groovy.lang.Closure), sort(boolean, groovy.lang.Closure), sort(boolean, java.util.Comparator)
        at co.freeside.betamax.tape.yaml.TapePropertyUtils.sort(TapeRepresenter.groovy:93)
        at co.freeside.betamax.tape.yaml.TapePropertyUtils.createPropertySet(TapeRepresenter.groovy:80)
        at org.yaml.snakeyaml.introspector.PropertyUtils.getProperties(PropertyUtils.java:101)
        at org.yaml.snakeyaml.introspector.PropertyUtils.getProperties(PropertyUtils.java:93)
        at org.yaml.snakeyaml.representer.Representer.getProperties(Representer.java:238)
        at co.freeside.betamax.tape.yaml.GroovyRepresenter.getProperties(GroovyRepresenter.groovy:28)
        at org.yaml.snakeyaml.representer.Representer$RepresentJavaBean.representData(Representer.java:49)
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:109)
        at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:65)
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:270)
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:261)
        at org.yaml.snakeyaml.Yaml.dump(Yaml.java:248)
        at co.freeside.betamax.tape.yaml.YamlTape.writeTo(YamlTape.groovy:48)
        at co.freeside.betamax.tape.yaml.YamlTapeLoader.writeTape_closure2(YamlTapeLoader.groovy:56)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:439)
        at co.freeside.betamax.tape.yaml.YamlTapeLoader.writeTape(YamlTapeLoader.groovy:54)
        at co.freeside.betamax.Recorder.ejectTape(Recorder.groovy:141)
        at co.freeside.betamax.Recorder.stopProxy(Recorder.groovy:205)
        at co.freeside.betamax.Recorder.withTape(Recorder.groovy:170)
        at co.freeside.betamax.Recorder$1.evaluate(Recorder.groovy:185)
        at org.spockframework.runtime.extension.builtin.MethodRuleInterceptor.intercept(MethodRuleInterceptor.java:40)
        at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:87)
        at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:59)
        at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:120)
        at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:103)
        at org.apache.maven.surefire.Surefire.run(Surefire.java:169)
        at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
        at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
```

I'm testing this against a freely available online REST demo site (http://www.predic8.com/rest-demo.htm) using Spock.  Here is a snippet of my code.  Any insight as to why this sort of exception is being thrown would be appreciated.

```java
import co.freeside.betamax.Betamax
import co.freeside.betamax.Recorder
import wslite.rest.ContentType
import wslite.rest.RESTClient
import wslite.rest.Response
import org.junit.Rule
import spock.lang.Specification

.
.
.

    // groovy-wslite
    Response response

    @Rule Recorder recorder = new Recorder()

    @Betamax(tape = "service directory of online demo")
    def 'Request service directory using online REST demo'() {
        def client

        given: "An online REST demo site"
        baseUrl = 'http://www.thomas-bayer.com'

        when: "The client accesses the services directory"
        client = new RESTClient(baseUrl)
        response = client.get(path: '/sqlrest', proxy: recorder.proxy)

        then: "The service shall respond with the appropriate data"
        println "RESPONSE CODE: ${response.statusCode}"
        println "RESPONSE STATUS MESSAGE: ${response.statusMessage}"
        println ''
        System.out << response
    }
```

**Comment by tomdcc** [comment] 2015-11-20 05:57
Just hit this too, using Groovy 2.4.4 and Betamax 1.1.2.

Weird thing is that `DefaultGroovyMethods` clearly has this method defined:
```groovy
    @Deprecated
    public static <T> List<T> sort(Collection<T> self, Comparator<T> comparator) {
        return sort((Iterable<T>) self, true, comparator);
    }
```

Though it IS deprecated...

**Comment by tomdcc** [comment] 2015-11-20 06:07
Oops, looks like this is a dupe of #141

**Comment by cowboygneox** [comment] 2016-02-17 12:56
This is a duplicate, and is likely a Groovy version conflict. This is not an issue in the 2.x release.

https://github.com/betamaxteam/betamax/issues/141

**Closed by cowboygneox** 2016-02-17 12:56 UTC
