### ISSUE TITLE
Handshake failure

### ISSUE THREAD

**Issue by xSAVIKx** [betamaxteam/betamax#175] opened 2016-02-25 22:00 UTC
Hi, I'm trying to use betamax 2.0-SNAPSHOT and for the given spock test:
```groovy
ProxyConfiguration configuration = ProxyConfiguration.builder()
            .tapeRoot(new File("src\\test\\resources\\betamax\\tapes"))
            .sslEnabled(true).build();
    @Rule
    public RecorderRule recorderRule = new RecorderRule(configuration);

    HttpClient customHttpClient

    def "setup"() {
        InetAddress address = configuration.getProxyHost()
        int proxyPort = configuration.getProxyPort()
        HttpHost host = new HttpHost(address, proxyPort, null)
        customHttpClient = HttpClientBuilder.create().setProxy(host).build()
    }

    @Betamax(tape = "test", mode = TapeMode.READ_WRITE)
    def "test"() {
        given:
        String query = "https://twingly.com/"
        HttpGet request = new HttpGet(query);
        when:
        HttpResponse response = customHttpClient.execute(request);
        BufferedReader rd = new BufferedReader(
                new InputStreamReader(response.getEntity().getContent()))
        def lines = rd.readLines()
        then:
        1 == 1
    }
```
I receive the following stacktrace with handshake failure:
```java
25, 2016 11:49:34 PM co.freeside.betamax.proxy.ProxyServer start
INFO: Betamax proxy is binding to /0.0.0.0:5555
0      2016-02-25 23:49:35,828 WARN  [LittleProxy-ProxyToServerWorker-0] impl.ProxyToServerConnection.exceptionCaught (ProxyToServerConnection.java:347) - (HANDSHAKING) [id: 0x65be4ec4, 0.0.0.0/0.0.0.0:52957 :> /80.252.171.80:443]: Caught exception on proxy -> web connection
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: handshake_failure
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:263)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:131)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:101)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634)
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:881)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:827)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:802)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:232)
	... 10 more
4      2016-02-25 23:49:35,832 WARN  [LittleProxy-ProxyToServerWorker-0] impl.ProxyToServerConnection.exceptionCaught (ProxyToServerConnection.java:350) - (HANDSHAKING) [id: 0x65be4ec4, 0.0.0.0/0.0.0.0:52957 :> /80.252.171.80:443]: Disconnecting open connection
```

Do you have any ideas what could be the reason ?
Without setting proxy directly on client creation Betamax just do nothing.

**Comment by cowboygneox** [comment] 2016-03-01 15:01
@xSAVIKx I'll look into this. I'm not sure what the issue is right now, but I can take what you've given me and go with it.

**Comment by xSAVIKx** [comment] 2016-03-01 15:37
@cowboygneox thanks.

**Comment by cowboygneox** [comment] 2016-03-06 18:05
@xSAVIKx from the looks of things, you're using an older SNAPSHOT than what master currently has. I'm assuming you built the SNAPSHOT locally, since we haven't actually put the SNAPSHOT on any maven distribution yet. Since we refactored the package name, I fixed a lot of the SSL issues the repo had. You should pull master again and rebuild with `./gradlew publishToMavenLocal` and let me know if you have any issues.

**Comment by cowboygneox** [comment] 2016-03-06 18:08
@xSAVIKx Also, you have to configure your proxy to use the Proxy. If you're using the 4.x version of Apache's HttpClient, then you can build it like this: `HttpClientBuilder.create().useSystemProperties().build()`.

**Comment by xSAVIKx** [comment] 2016-03-09 09:23
@cowboygneox Actually, I've used snapshot from [oss-snapshot-local](http://oss.jfrog.org/oss-snapshot-local/:).
You can check my [gradle.build
](https://github.com/xSAVIKx/twingly-search-api-java/blob/a07a4995912e74fc66687efca1ac3e5ecbc32bc0/build.gradle)

**Comment by cowboygneox** [comment] 2016-03-09 17:43
@xSAVIKx It's the wrong groupId; software.betamax is the correct one. Please see the [alpha release](https://github.com/betamaxteam/betamax/releases/tag/2.0.0-alpha-1).

**Comment by cowboygneox** [comment] 2016-03-09 17:43
We haven't used @robfletcher's domain in a while now.

**Comment by xSAVIKx** [comment] 2016-03-12 07:23
@cowboygneox Hi.
I've tried alpha release and I think this issue should be closed now, thanks for your time.
And about groupId - I've tried info from here: [betamax with java 8](http://hexcoder.us/2015/04/11/betamax-testing-with-java-8/).

And also one more question: is betamax compiled with java 8 ? Cause I'm now having troubles running it under java 7, but everything is OK with java 8.

**Comment by cowboygneox** [comment] 2016-03-14 01:01
@xSAVIKx it is compiled with Java8, but it's supposed to be backwards compatible. I'll fix that.

**Comment by cowboygneox** [comment] 2016-03-14 01:03
@xSAVIKx I'm closing this. The bug you found is now captured in #186.

**Closed by cowboygneox** 2016-03-14 01:03 UTC
Labels: triage

**Comment by xSAVIKx** [comment] 2016-03-14 05:45
So, please, close also: #185 when it'll be fixed.
